name: Supabase Migrations + Vercel (single env)
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/lib/database.types.ts'
  workflow_dispatch:
concurrency:
  group: db-single-${{ github.ref }}
  cancel-in-progress: false
permissions:
  contents: read
jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with: { version: latest }

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Apply migrations
        run: supabase db push
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Generate TypeScript types
        run: supabase gen types typescript --linked --schema public > src/lib/database.types.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Trigger Vercel deploy
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
