name: Deploy Stage (Vercel Hook)

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy en Vercel (branch stage)
        env:
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL_STAGE }}
        run: |
          if [ -z "$HOOK" ]; then
            echo "No hay VERCEL_DEPLOY_HOOK_URL_STAGE. Saliendo con éxito (no-op)."
            exit 0
          fi
          curl -X POST "$HOOK"
